/*
 * File: app/store/ClientStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('myMDAnderson.store.MenuStore', {
	extend : 'Ext.data.Store',

	config: {
	storeId: 'menuStore',
	model : 'myMDAnderson.model.MenuModel',
    autoload: true,
    //data:[{title:'FAQ'},{title:'help'}]

    proxy: {
        type: 'rest',
        url: 'resources/config/menu.json',
            reader: {
        type: 'json', 
      },     
     }
}
});